- name: "Install nginx"
  hosts: node
  become: yes
  tasks:
    - name: "Install the nginx service"
      ansible.builtin.package: 
        name: nginx
        state: present
        
    - name: "Start nginx"
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
