- name: "Variables"
  hosts: local
  connection: local
  vars:
    COURSE: "DevOPS with AWS"
    DURATION: "140hrs"
    Trainer: "Shiva kumar reddy"
  tasks:
  - name: "Learning devops"
    ansible.builin.debug:
      msg : "Course is : {{ COURSE }}, Trainer is: {{ Trainer }}"