- name: play level variables
  hosts: local
  connection: local
  vars:
    Course: "Devops with aws"
    Duration: "3 months"
    Trainer: "Yashwanth"  
    tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "course is: {{ Course }}, duration is: {{ Duration }}, trainer is: {{ Trainer }}"
