- name: play level variables
  hosts: local
  connection: local
  vars:
    Name: "Ansible form play level"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter name
    private: false
  tasks:
  - name: Print name
    vars:
      Name: "Ansible form task level"
    ansible.builtin.debug:
      msg: "HI {{ NAME }}" 
