- name: "Demo on conditions"
  hosts: local
  connection: local
  vars:
    Number_of_sessions: 7
  tasks:
    - name: "check sessions greater than 5 or not"
      ansible.builtin.debug:
        msg: "Yes sessions are greater than 5"
      when: Number_of_sessions -gt 5