- name : check a number is greater than 10 or not
  hoste: local
  connection: local
  vars:
    NUMBER: 10
  tasks:
  - name: check number is greater than 10 or not
    ansible.builtin.debug:
      msg: "Number is greater than 10"
    when: NUMBER > 5