- name: "demo on install package"
  hosts: local
  become: yes
  connection: local
  tasks:
    - name: "Demo on install package"
      ansible.builtin.package:
        name : "{{ item }}"
        state: present
      loop:
      - { name: "mysql", state: "absent"}
      - { name: "nginx", state: "present"}
      - { name: "zip", state: "absent"}
