- name: install packages using loop
  hosts: local
  connection: local
  became: true
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - mysql
      - nginx
      - zip
