- name: "Demo on conditons"
  hosts: local
  connection: local
  vars:
    name: "ram,rahim,robert,ramesh,suresh"
    tagsMap:
      name1: "Yashwanth"
      project: "Roboshop"
      component: "Frontend"
    tagslist:
       [
        {
            "key": "name1",
            "value": "Yashwanth"
        },
        {
            "key": "project",
            "value": "Roboshop"
        },
        {
            "key": "component",
            "value": "Frontend"
        }
    ]

  tasks:
    - name: "Demo on conditions"
      ansible.builtin.debug:
        msg: "Hello {{ Greeting | default('Good morning') }}"
      
    - name: "convert String to list"
      ansible.builtin.debug:
        msg: "{{ name | split(',') }}"

    - name: "convert map to list"
      ansible.builtin.debug:
        msg: "{{ tagsMap |  dict2items }}"

    - name: "convert list to maps"
      ansible.builtin.debug:
        msg: "{{ tagslist | items2dict }}"

    - name: "Read yaml to variable"
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

    - name: "convert yaml to json"
      ansible.builtin.debug: 
        msg: "{{ student_yaml | to_nice_json }}"